<?php

namespace App\Constraint;

use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\ConstraintValidator;

class RegistrationYearAssert extends Constraint
{
    public function validatedBy()
    {
        return parent::validatedBy(); // TODO: Change the autogenerated stub
    }
}

class RegistrationYearValidator extends ConstraintValidator
{
    public function validate($value, Constraint $constraint)
    {

    }

}